export const FETCH_MEAL_TYPE = 'FETCH_MEAL_TYPE';
export const FETCH_MEAL_TYPE_FAILED = 'FETCH_MEAL_TYPE_FAILED';
export const FETCH_MEAL_TYPE_DETAIL = 'FETCH_MEAL_TYPE_DETAIL';

export const FETCH_CUISINE_TYPE = 'FETCH_CUISINE_TYPE';
export const FETCH_CUISINE_TYPE_FAILED = 'FETCH_CUISINE_TYPE_FAILED';